### PR TITLE
[PBW-4213] Added BITRATE_CONTROL constant for OO.VIDEO.FEATURE block

### PR DESCRIPTION
**Pull request by mityaha**

### CODE REVIEW

**Comment by angieisrani** [comment]
@chibzu Had made additional changes to constants.js in the internal player repo.  Dustin, can you merge all changes?  This is one of three I think

**Comment by aldigun** [comment]
I am about to add a new Pull request that Dustin made in internal repo.

**Comment by aldigun** [comment]
Pull request is here:
https://github.com/ooyala/html5-common/pull/19

**Comment by aldigun** [comment]
is this needed with #19 ? If not, feel free to close this PR :)

**Comment by angieisrani** [comment]
Closing in favor of the other pull request with all changes for bitrate

**Pull request closed without merging**
