### PR TITLE
Feature/player 2104

### PR DESCRIPTION
**Pull request by KseniiaSokolovaEpam**
Way to check if $ exists was changed. No unit tests.

For testing I used code below:
```html
<!DOCTYPE html>
<html>
<head data-noxhrfix>
  <meta charset="utf-8">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
</head>

<body>

<div style="padding-bottom:1em;">
<div><b>BEFORE CALLING OOYALA</b></div>
<ul>
<li>The <i>jQuery</i> variable is <span id='jQuery-before'><b>BROKEN</b>!</span></li>
<li>The <i>$</i> variable is <span id='dollar-before'><b>BROKEN</b>!</span></li>
<li>"$ === jQuery" is <span id="eq-before"></span></li>
</ul>
<script>
try { jQuery("#jQuery-before").html("fine. jQuery version is " + jQuery.fn.jquery); } catch(ex) { }
try { $("#dollar-before").html("fine. $ version is " + $.fn.jquery); } catch(ex) { }
var eqBefore = document.getElementById("eq-before");
try { eqBefore.innerHTML = ($ === jQuery).toString(); } catch(ex) { }
</script>
</div>

<script src="//player.ooyala.com/static/v4/production/core.js"></script>
<script src="//192.168.1.112:8000/html5-ad-plugins/build/ad_manager_vast.js"></script>

<div style="padding-bottom:1em;">
<div><b>AFTER CALLING OOYALA</b></div>
<ul>
<li>The <i>jQuery</i> variable is <span id='jQuery-after'><b>BROKEN</b>!</span></li>
<li>The <i>$</i> variable is <span id='dollar-after'><b>BROKEN</b>!</span></li>
<li>"$ === jQuery" is <span id="eq-after"></span></li>
</ul>
<script>
try { jQuery("#jQuery-after").html("fine. jQuery version is " + jQuery.fn.jquery); } catch(ex) { }
try { $("#dollar-after").html("fine. $ version is " + $.fn.jquery); } catch(ex) { }

var eqAfter = document.getElementById("eq-after");
try { eqAfter.innerHTML = ($ === jQuery).toString(); } catch(ex) { }

</script>
</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

<div style="padding-bottom:1em;">
  <div><b>AFTER CALLING OOYALA 2</b></div>
  <ul>
    <li>The <i>jQuery</i> variable is <span id='jQuery-after2'><b>BROKEN</b>!</span></li>
    <li>The <i>$</i> variable is <span id='dollar-after2'><b>BROKEN</b>!</span></li>
    <li>"$ === jQuery" is <span id="eq-after2"></span></li>
  </ul>
  <script>
    try { jQuery("#jQuery-after2").html("fine. jQuery version is " + jQuery.fn.jquery); } catch(ex) { }
    try { $("#dollar-after2").html("fine. $ version is " + $.fn.jquery); } catch(ex) { }
    var eqAfter2 = document.getElementById("eq-after2");
    try { eqAfter2.innerHTML = ($ === jQuery).toString(); } catch(ex) { }
  </script>
</div>

</body>
</html>
```

Result 
```
BEFORE CALLING OOYALA

    The jQuery variable is fine. jQuery version is 3.2.1
    The $ variable is fine. $ version is 3.2.1
    "$ === jQuery" is true

AFTER CALLING OOYALA

    The jQuery variable is fine. jQuery version is 2.1.3
    The $ variable is fine. $ version is 2.1.3
    "$ === jQuery" is true

AFTER CALLING OOYALA 2

    The jQuery variable is fine. jQuery version is 3.2.1
    The $ variable is fine. $ version is 3.2.1
    "$ === jQuery" is true
```

### CODE REVIEW

**Comment by jpfranco** [comment]
@KseniiaSokolovaEpam the code updates look good but I have a question. Should the version of the global jQuery change after loading the player? It's possible that the customer might rely on specific jquery features on the rest of the page, so changing the version might cause some conflicts. @aldigun @aeng7 do we know what is expected here?

Please also make sure to test a scenario where jQuery does not exist before the player is loaded since this is the case where the reference error could occur. Thanks

**Comment by aeng7** [comment]
I believe the jQuery version on the page should not change for the same reasons @jpfranco has given.

**Comment by aldigun** [comment]
I believe our jquery should be isolated to our own space. I wonder why we did a window assigment there.

**Comment by jpfranco** [comment]
@KseniiaSokolovaEpam @DmitriiMaslov I think in it's current state this update would not meet the acceptance criteria from the ticket, since the original jQuery version is changed:

> Make sure $.fn.jquery and jQuery.fn.jquery are having the same version to the loaded jquery on the page.

Please review and let us know whether this is the case. Thanks

**Comment by KseniiaSokolovaEpam** [comment]
@jpfranco 
Now I see two ways to fix the essue:
the first way is to remove 'true' from noConflict in original code in InitOOJQuery
the second is to do something like that
```
if (! (OO.jQuery && OO. $)) {
   OO.jQuery = require ('jquery');
   OO. $ = Require ('jquery');
}
```

But I tried to check the version of jQuery inside of ad_manager_vast (like that
OO.$.fn.jquery and $ .fn.jquery). Versions in the first variant are 1.8.3 and 1.8.3, and they are 2.1.3 and 1.8.3 in the second variant . I think that version should be 2.1.3 because this version of jQuery is in package.json 
But I can not get why we have 1.8.3.
Do you have any idea why it happend?
Thanks!

**Comment by jpfranco** [comment]
@KseniiaSokolovaEpam hmm not sure, I would need to take a closer look. I think in general what we need is that the version of `window.$` is the one loaded by the page and the version of `OO.$` is the one from our build process. Is that what you're seeing in your tests?

**Comment by KseniiaSokolovaEpam** [comment]
@jpfranco 
I got why i saw version 1.8.3, that happens because skin uses v 1.8.3.
So, I save variant when OO.$.fn.jquery is 2.1.3 (there is 2.1.3 in package.json for html5-ad-plugins).

Test page is

```
<!DOCTYPE html>
<html>
<head data-noxhrfix>
  <meta charset="utf-8">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

  <link rel="stylesheet" href="//localhost:8000/html5-skin/build/html5-skin.min.css"/>
  <script src="//localhost:8000/new/mjolnir/build/mjolnir.js"></script>
  <script src="//localhost:8000/video-plugins-internal/build/bit_wrapper.js"></script>
  <script src="//localhost:8000/html5-video-plugins/build/main_html5.js"></script>
  <script src="//player.ooyala.com/static/v4/production/video-plugin/osmf_flash.min.js"></script>
  <script src="//localhost:8000/html5-skin/build/html5-skin.js"></script>
</head>

<body>

<div style="padding-bottom:1em;">
<div><b>BEFORE CALLING OOYALA</b></div>
<ul>
<li>The <i>jQuery</i> variable is <span id='jQuery-before'><b>BROKEN</b>!</span></li>
<li>The <i>$</i> variable is <span id='dollar-before'><b>BROKEN</b>!</span></li>
<li>"$ === jQuery" is <span id="eq-before"></span></li>
</ul>
<script>
try { jQuery("#jQuery-before").html("fine. jQuery version is " + jQuery.fn.jquery); } catch(ex) { }
try { $("#dollar-before").html("fine. $ version is " + $.fn.jquery); } catch(ex) { }
var eqBefore = document.getElementById("eq-before");
try { eqBefore.innerHTML = ($ === jQuery).toString(); } catch(ex) { }
</script>
</div>

<script src="//localhost:8000/html5-ad-plugins/build/ad_manager_vast.js"></script>

<!--<script src="//localhost:8000/html5-ad-plugins/build/ssai_pulse.js"></script>-->

<div id='container' style='width:500px; display: inline-block;'></div>
<script>
  var playerParam = {
    "pcode": 'BzY2syOq6kIK6PTXN7mmrGVSJEFj',
    "playerBrandingId": 'ab50defe233a455388e8b3b74797f9f9',
    "debug": true
  };
  OO.ready(function() {
    window.pp = OO.Player.create('container', 'pjb25lZDE6f9jZidxXeR79PpN9ORKQId', playerParam);
  });
</script>

<!--<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.0/jquery.min.js"></script>-->

<div style="padding-bottom:1em;">
  <div><b>AFTER CALLING OOYALA</b></div>
  <ul>
    <li>The <i>jQuery</i> variable is <span id='jQuery-after2'><b>BROKEN</b>!</span></li>
    <li>The <i>$</i> variable is <span id='dollar-after2'><b>BROKEN</b>!</span></li>
    <li>"$ === jQuery" is <span id="eq-after2"></span></li>
  </ul>
  <script>
    try { jQuery("#jQuery-after2").html("fine. jQuery version is " + jQuery.fn.jquery); } catch(ex) { }
    try { $("#dollar-after2").html("fine. $ version is " + $.fn.jquery); } catch(ex) { }
    var eqAfter2 = document.getElementById("eq-after2");
    try { eqAfter2.innerHTML = ($ === jQuery).toString(); } catch(ex) { }
  </script>
</div>

</body>
</html>
```

**Comment by jpfranco** [comment]
@KseniiaSokolovaEpam I created another test page and this is what I'm seeing when building the SSAI plugin using the branch from this PR:

screen shot 2018-04-19 at 1 49 09 pm

So it looks like the global `$` loaded by the customer and the internal `OO.$` loaded by the Player core are being replaced by the version loaded by the SSAI plugin. We don't want to change the version of the global jQuery because this might break the customer's implementation.

This is the test page that I'm using:
```html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

  <script>
    console.log(">>>>----External jQuery");
    console.log("$.fn.jquery", $.fn.jquery);
    console.log("jQuery.fn.jquery", jQuery.fn.jquery);
  </script>

  <link rel="stylesheet" href="//player.ooyala.com/static/v4/candidate/latest/skin-plugin/html5-skin.min.css"/>
  <script src="//player.ooyala.com/static/v4/candidate/latest/core.min.js"></script>
  <script src="//player.ooyala.com/static/v4/candidate/latest/video-plugin/bit_wrapper.min.js"></script>
  <script src="//player.ooyala.com/static/v4/candidate/latest/video-plugin/main_html5.min.js"></script>
  <script src="//player.ooyala.com/static/v4/candidate/latest/skin-plugin/html5-skin.min.js"></script>

  <script>
    console.log(">>>>----After Main Player Scripts Loaded----<<<<");
    console.log("$.fn.jquery", $.fn.jquery);
    console.log("jQuery.fn.jquery", jQuery.fn.jquery);
    console.log("OO.$.fn.jquery", OO.$.fn.jquery);
    console.log("OO.jQuery.fn.jquery", OO.jQuery ? OO.jQuery.fn.jquery : undefined );
  </script>

  <script src="//player.ooyala.com/static/v4/production/latest/ad-plugin/ssai_pulse.min.js"></script>
  <!-- <script src="//localhost:8000/repos/html5-ad-plugins/build/ssai_pulse.js"></script> -->

  <script>
    console.log(">>>>----After SSAI Script Loaded----<<<<");
    console.log("$.fn.jquery", $.fn.jquery);
    // console.log("jQuery.fn.jquery", jQuery.fn.jquery);
    console.log("OO.$.fn.jquery", OO.$.fn.jquery);
    console.log("OO.jQuery.fn.jquery", OO.jQuery ? OO.jQuery.fn.jquery : undefined );
  </script>
</head>
<body>

  <div id='container' style='width:640px;'></div>

  <script>
    var playerParams = {
      pcode: 'BzY2syOq6kIK6PTXN7mmrGVSJEFj',
      playerBrandingId: 'ab50defe233a455388e8b3b74797f9f9',
      debug: false
    };
    OO.ready(function() {
      OO.Player.create('container', 'pjb25lZDE6f9jZidxXeR79PpN9ORKQId', playerParams);
    });
  </script>

</body>
</html>
```

**Comment by jpfranco** [comment]
@KseniiaSokolovaEpam this needs confirmation, but I'm starting to suspect that what the original author of the code did was not needed. If you take a look at the ad plugin code, you'll see that jQuery is passed to the `OO.Ads.manager` function.

screen shot 2018-04-19 at 2 59 51 pm

In the code of the core we can see that `OO.Ads.manager` passes the `$` variable from its own scope, which is the one loaded by mjolnir (`OO.$`):

screen shot 2018-04-19 at 4 55 47 pm

It looks like the ad plugins are actually using the 1.8.3 version that is loaded by mjolnir instead of the 3.2.1 version from html5-common. If this is true then this jquery initialization code from html5-common is not needed.

Can you help me confirm? If this is true then we can probably fix the issue by simply removing this line from `ad_manager_vast` and `ssai_pulse` plugins (it's used in both):

```
require("../html5-common/js/utils/InitModules/InitOOJQuery.js");
```

**Comment by jpfranco** [comment]
Closing since we will be using a different approach for this fix.

**Pull request closed without merging**
