### PR TITLE
[PBW-4237] Matched bitrate events to internal core.

### PR DESCRIPTION
**Pull request by aldigun**

### CODE REVIEW

**Comment by angieisrani** [comment]
@aldigun did you purposely exclude the feature?

**Comment by aldigun** [comment]
which feature?

**Comment by mityaha** [comment]
BITRATE_CONTROL

**Comment by aldigun** [comment]
haha sorry folks, Looks like there is confusion here. I wasn't aware we added BITRATE_CONTROL when I began this. Will add that as well on next commit shortly.

**Comment by aldigun** [comment]
Okay, BITRATE_CONTROL is added now. Thanks for the reminder :)

**Comment by angieisrani** [comment]
LGTM

**Comment by angieisrani** [comment]
@aldigun I just realized the jsdocs are missing the field names for the bitrate objects

**Pull request merged**
